//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.19 at 01:14:38 PM CET 
//


package com.comparadorad.bet.comparer.synchro.reader.readerbookmaker.bean.nordicbet;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}Sport"/>
 *         &lt;element ref="{}Region"/>
 *         &lt;element ref="{}Season"/>
 *         &lt;element ref="{}BreadCrumbs"/>
 *         &lt;element ref="{}GameStartTime"/>
 *         &lt;element ref="{}BettingEndTime"/>
 *         &lt;element ref="{}LiveBet"/>
 *         &lt;element ref="{}Participant" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}OutcomeSet" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sport",
    "region",
    "season",
    "breadCrumbs",
    "gameStartTime",
    "bettingEndTime",
    "liveBet",
    "participant",
    "outcomeSet"
})
@XmlRootElement(name = "Game")
public class Game {

    @XmlElement(name = "Sport", required = true)
    protected String sport;
    @XmlElement(name = "Region", required = true)
    protected String region;
    @XmlElement(name = "Season", required = true)
    protected String season;
    @XmlElement(name = "BreadCrumbs", required = true)
    protected String breadCrumbs;
    @XmlElement(name = "GameStartTime", required = true)
    protected String gameStartTime;
    @XmlElement(name = "BettingEndTime", required = true)
    protected String bettingEndTime;
    @XmlElement(name = "LiveBet", required = true)
    protected String liveBet;
    @XmlElement(name = "Participant")
    protected List<Participant> participant;
    @XmlElement(name = "OutcomeSet", required = true)
    protected List<OutcomeSet> outcomeSet;
    @XmlAttribute(name = "name", required = true)
    protected String name;
    @XmlAttribute(name = "id", required = true)
    protected long id;

    /**
     * Gets the value of the sport property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSport() {
        return sport;
    }

    /**
     * Sets the value of the sport property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSport(String value) {
        this.sport = value;
    }

    /**
     * Gets the value of the region property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegion() {
        return region;
    }

    /**
     * Sets the value of the region property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegion(String value) {
        this.region = value;
    }

    /**
     * Gets the value of the season property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSeason() {
        return season;
    }

    /**
     * Sets the value of the season property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSeason(String value) {
        this.season = value;
    }

    /**
     * Gets the value of the breadCrumbs property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBreadCrumbs() {
        return breadCrumbs;
    }

    /**
     * Sets the value of the breadCrumbs property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBreadCrumbs(String value) {
        this.breadCrumbs = value;
    }

    /**
     * Gets the value of the gameStartTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGameStartTime() {
        return gameStartTime;
    }

    /**
     * Sets the value of the gameStartTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGameStartTime(String value) {
        this.gameStartTime = value;
    }

    /**
     * Gets the value of the bettingEndTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBettingEndTime() {
        return bettingEndTime;
    }

    /**
     * Sets the value of the bettingEndTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBettingEndTime(String value) {
        this.bettingEndTime = value;
    }

    /**
     * Gets the value of the liveBet property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLiveBet() {
        return liveBet;
    }

    /**
     * Sets the value of the liveBet property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLiveBet(String value) {
        this.liveBet = value;
    }

    /**
     * Gets the value of the participant property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the participant property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getParticipant().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Participant }
     * 
     * 
     */
    public List<Participant> getParticipant() {
        if (participant == null) {
            participant = new ArrayList<Participant>();
        }
        return this.participant;
    }

    /**
     * Gets the value of the outcomeSet property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the outcomeSet property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOutcomeSet().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OutcomeSet }
     * 
     * 
     */
    public List<OutcomeSet> getOutcomeSet() {
        if (outcomeSet == null) {
            outcomeSet = new ArrayList<OutcomeSet>();
        }
        return this.outcomeSet;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the id property.
     * 
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(long value) {
        this.id = value;
    }

}
