//
// Este archivo ha sido generado por la arquitectura JavaTM para la implantación de la referencia de enlace (JAXB) XML v2.2.6 
// Visite <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Todas las modificaciones realizadas en este archivo se perderán si se vuelve a compilar el esquema de origen. 
// Generado el: PM.06.03 a las 04:13:49 PM CEST 
//


package com.comparadorad.bet.comparer.synchro.reader.readerbookmaker.bean.betredkings;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Clase Java para anonymous complex type.
 * 
 * <p>El siguiente fragmento de esquema especifica el contenido que se espera que haya en esta clase.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="type">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="away"/>
 *             &lt;enumeration value="home"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="name" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="1. FSV Mainz 05"/>
 *             &lt;enumeration value="1. HFK Olomouc"/>
 *             &lt;enumeration value="1.FC Nurnberg"/>
 *             &lt;enumeration value="AA Ponte Preta"/>
 *             &lt;enumeration value="AB Copenhagen"/>
 *             &lt;enumeration value="ABC Futebol Clube"/>
 *             &lt;enumeration value="AC Horsens"/>
 *             &lt;enumeration value="AC Kajaani"/>
 *             &lt;enumeration value="AD São Caetano do Sul"/>
 *             &lt;enumeration value="AGF Aarhus"/>
 *             &lt;enumeration value="AIFK Turku"/>
 *             &lt;enumeration value="AIK"/>
 *             &lt;enumeration value="ASA (Agremiação Sportiva Arapiraquense)"/>
 *             &lt;enumeration value="AaB Aalborg"/>
 *             &lt;enumeration value="Aalesunds FK"/>
 *             &lt;enumeration value="Aarhus Fremad"/>
 *             &lt;enumeration value="Albania"/>
 *             &lt;enumeration value="Albania U21"/>
 *             &lt;enumeration value="Algeria"/>
 *             &lt;enumeration value="Alianza Lima"/>
 *             &lt;enumeration value="Alianza Petrolera"/>
 *             &lt;enumeration value="Allerod FK"/>
 *             &lt;enumeration value="Alleso GF"/>
 *             &lt;enumeration value="Almirante Brown"/>
 *             &lt;enumeration value="Alta IF"/>
 *             &lt;enumeration value="Alviks IK"/>
 *             &lt;enumeration value="America Mineiro"/>
 *             &lt;enumeration value="America RN (Rio Grande do Norte)"/>
 *             &lt;enumeration value="Andorra U21"/>
 *             &lt;enumeration value="Angelholms FF"/>
 *             &lt;enumeration value="Angola"/>
 *             &lt;enumeration value="Argentina"/>
 *             &lt;enumeration value="Armenia"/>
 *             &lt;enumeration value="Armenia U21"/>
 *             &lt;enumeration value="Arsenal"/>
 *             &lt;enumeration value="Assyriska Föreningen"/>
 *             &lt;enumeration value="Aston Villa"/>
 *             &lt;enumeration value="Athlone Town FC"/>
 *             &lt;enumeration value="Atletico Clube Goianiense"/>
 *             &lt;enumeration value="Atletico Mineiro"/>
 *             &lt;enumeration value="Atletico Paranaense"/>
 *             &lt;enumeration value="Atletico Tucuman"/>
 *             &lt;enumeration value="Aumund-Vegesack"/>
 *             &lt;enumeration value="Australia"/>
 *             &lt;enumeration value="Austria"/>
 *             &lt;enumeration value="Austria U21"/>
 *             &lt;enumeration value="Avai"/>
 *             &lt;enumeration value="Avedore"/>
 *             &lt;enumeration value="Azerbaijan"/>
 *             &lt;enumeration value="Azerbaijan U21"/>
 *             &lt;enumeration value="B 1908"/>
 *             &lt;enumeration value="BK Häcken"/>
 *             &lt;enumeration value="BK Sollerod-Vedbaek"/>
 *             &lt;enumeration value="BK-46"/>
 *             &lt;enumeration value="BSV"/>
 *             &lt;enumeration value="Banfield"/>
 *             &lt;enumeration value="Barnsley FC"/>
 *             &lt;enumeration value="Bayer 04 Leverkusen"/>
 *             &lt;enumeration value="Belarus"/>
 *             &lt;enumeration value="Belarus U21"/>
 *             &lt;enumeration value="Belgium"/>
 *             &lt;enumeration value="Belgium U21"/>
 *             &lt;enumeration value="Benin"/>
 *             &lt;enumeration value="Birmingham City FC"/>
 *             &lt;enumeration value="Blackburn Rovers"/>
 *             &lt;enumeration value="Blackpool FC"/>
 *             &lt;enumeration value="Blokhus"/>
 *             &lt;enumeration value="Boa Ec"/>
 *             &lt;enumeration value="Boca Unidos"/>
 *             &lt;enumeration value="Bohemians 1905"/>
 *             &lt;enumeration value="Bohemians FC"/>
 *             &lt;enumeration value="Bohemians Prague"/>
 *             &lt;enumeration value="Boler"/>
 *             &lt;enumeration value="Bolivia"/>
 *             &lt;enumeration value="Bolton Wanderers"/>
 *             &lt;enumeration value="Borbjerg GU"/>
 *             &lt;enumeration value="Borussia Dortmund"/>
 *             &lt;enumeration value="Borussia Monchengladbach"/>
 *             &lt;enumeration value="Bosnia and Herzegovina"/>
 *             &lt;enumeration value="Bosnia and Herzegowina U21"/>
 *             &lt;enumeration value="Botafogo RJ"/>
 *             &lt;enumeration value="Botswana"/>
 *             &lt;enumeration value="Bournemouth FC"/>
 *             &lt;enumeration value="Brabrand IF"/>
 *             &lt;enumeration value="Bradford City"/>
 *             &lt;enumeration value="Bray Wanderers AFC"/>
 *             &lt;enumeration value="Brazil"/>
 *             &lt;enumeration value="Breidablik Kopavogur"/>
 *             &lt;enumeration value="Bremer SV"/>
 *             &lt;enumeration value="Brentford"/>
 *             &lt;enumeration value="Brighton and Hove Albion"/>
 *             &lt;enumeration value="Bristol City FC"/>
 *             &lt;enumeration value="Brondby I.F."/>
 *             &lt;enumeration value="Bronshoj BK"/>
 *             &lt;enumeration value="Bulgaria"/>
 *             &lt;enumeration value="Bulgaria U19"/>
 *             &lt;enumeration value="Bulgaria U21"/>
 *             &lt;enumeration value="Burkina Faso"/>
 *             &lt;enumeration value="Burnley FC"/>
 *             &lt;enumeration value="Bury"/>
 *             &lt;enumeration value="Bury Town FC"/>
 *             &lt;enumeration value="CA All Boys"/>
 *             &lt;enumeration value="CR Flamengo"/>
 *             &lt;enumeration value="CR Vasco da Gama"/>
 *             &lt;enumeration value="CSC"/>
 *             &lt;enumeration value="Cameroon"/>
 *             &lt;enumeration value="Cape Verde"/>
 *             &lt;enumeration value="Cardiff City FC"/>
 *             &lt;enumeration value="Carlisle United"/>
 *             &lt;enumeration value="Ceara CE"/>
 *             &lt;enumeration value="Central African Republic"/>
 *             &lt;enumeration value="Ceske Budejovice U21"/>
 *             &lt;enumeration value="Chang"/>
 *             &lt;enumeration value="Chapecoense AF"/>
 *             &lt;enumeration value="Charlton Athletic FC"/>
 *             &lt;enumeration value="Chelsea"/>
 *             &lt;enumeration value="Chile"/>
 *             &lt;enumeration value="China"/>
 *             &lt;enumeration value="Club Deportivo Los Millonarios"/>
 *             &lt;enumeration value="Clube Atlético Bragantino"/>
 *             &lt;enumeration value="Cobh Ramblers"/>
 *             &lt;enumeration value="Colchester United FC"/>
 *             &lt;enumeration value="Colombia"/>
 *             &lt;enumeration value="Colombia U20"/>
 *             &lt;enumeration value="Columbus Crew"/>
 *             &lt;enumeration value="Congo"/>
 *             &lt;enumeration value="Congo DR"/>
 *             &lt;enumeration value="Congo DR U20"/>
 *             &lt;enumeration value="Corinthians Paulista"/>
 *             &lt;enumeration value="Coritiba FBC"/>
 *             &lt;enumeration value="Cork City FC"/>
 *             &lt;enumeration value="Costa Rica"/>
 *             &lt;enumeration value="Cote d'Ivoire"/>
 *             &lt;enumeration value="Coventry City FC"/>
 *             &lt;enumeration value="Crawley Town"/>
 *             &lt;enumeration value="Crewe Alexandra"/>
 *             &lt;enumeration value="Criciuma EC"/>
 *             &lt;enumeration value="Croatia"/>
 *             &lt;enumeration value="Croatia U19"/>
 *             &lt;enumeration value="Croatia U21"/>
 *             &lt;enumeration value="Crucero del Norte"/>
 *             &lt;enumeration value="Cruzeiro EC Belo Horizonte"/>
 *             &lt;enumeration value="Crystal Palace FC"/>
 *             &lt;enumeration value="Cyprus"/>
 *             &lt;enumeration value="Cyprus U19"/>
 *             &lt;enumeration value="Cyprus U21"/>
 *             &lt;enumeration value="Czech Republic"/>
 *             &lt;enumeration value="Czech Republic U19"/>
 *             &lt;enumeration value="DGL 2000 Aarhus"/>
 *             &lt;enumeration value="Defensa y Justicia"/>
 *             &lt;enumeration value="Denmark"/>
 *             &lt;enumeration value="Denmark U19"/>
 *             &lt;enumeration value="Denmark U21"/>
 *             &lt;enumeration value="Derby County"/>
 *             &lt;enumeration value="Derry City"/>
 *             &lt;enumeration value="Djurgårdens IF"/>
 *             &lt;enumeration value="Doncaster Rovers"/>
 *             &lt;enumeration value="Drammen FK"/>
 *             &lt;enumeration value="Drogheda United"/>
 *             &lt;enumeration value="Dukla Praha U21"/>
 *             &lt;enumeration value="Dundalk FC"/>
 *             &lt;enumeration value="EC Bahia"/>
 *             &lt;enumeration value="EC Vitoria"/>
 *             &lt;enumeration value="Ecuador"/>
 *             &lt;enumeration value="Egebjerg IF"/>
 *             &lt;enumeration value="Egypt"/>
 *             &lt;enumeration value="Eintracht Frankfurt"/>
 *             &lt;enumeration value="Elite 3000 Helsingor"/>
 *             &lt;enumeration value="England U21"/>
 *             &lt;enumeration value="Equatorial Guinea"/>
 *             &lt;enumeration value="Esbjerg F.B."/>
 *             &lt;enumeration value="Esbjerg IF 92"/>
 *             &lt;enumeration value="Espa"/>
 *             &lt;enumeration value="Estonia"/>
 *             &lt;enumeration value="Estonia U21"/>
 *             &lt;enumeration value="Ethiopia"/>
 *             &lt;enumeration value="Everton"/>
 *             &lt;enumeration value="FBC Melgar Arequipa"/>
 *             &lt;enumeration value="FC Augsburg"/>
 *             &lt;enumeration value="FC Bayern Munchen"/>
 *             &lt;enumeration value="FC Bremerhaven"/>
 *             &lt;enumeration value="FC Brno U21"/>
 *             &lt;enumeration value="FC Burg"/>
 *             &lt;enumeration value="FC Fredericia"/>
 *             &lt;enumeration value="FC Fyn"/>
 *             &lt;enumeration value="FC Graffin Vlasim"/>
 *             &lt;enumeration value="FC Haka Valkeakoski"/>
 *             &lt;enumeration value="FC Kobenhavn"/>
 *             &lt;enumeration value="FC Midtjylland"/>
 *             &lt;enumeration value="FC Nordsjaelland"/>
 *             &lt;enumeration value="FC Nordvest"/>
 *             &lt;enumeration value="FC Roskilde"/>
 *             &lt;enumeration value="FC Schalke 04"/>
 *             &lt;enumeration value="FC Sonderborg"/>
 *             &lt;enumeration value="FC Vestsjaelland "/>
 *             &lt;enumeration value="FC Zenit Caslav"/>
 *             &lt;enumeration value="FC Zlin"/>
 *             &lt;enumeration value="FH Hafnarfjordur"/>
 *             &lt;enumeration value="FK Banik Most"/>
 *             &lt;enumeration value="FK Banik Sokolov"/>
 *             &lt;enumeration value="FK Dainava"/>
 *             &lt;enumeration value="FK Haugesund"/>
 *             &lt;enumeration value="FK Siauliai"/>
 *             &lt;enumeration value="FK Spartak Nalchik"/>
 *             &lt;enumeration value="FK Spartak Sezimovo Usti"/>
 *             &lt;enumeration value="FK Usti nad Labem"/>
 *             &lt;enumeration value="FK Viktoria Zizkov"/>
 *             &lt;enumeration value="FYR of Macedonia"/>
 *             &lt;enumeration value="FYR of Macedonia U21"/>
 *             &lt;enumeration value="Falkenbergs FF"/>
 *             &lt;enumeration value="Faroe Islands"/>
 *             &lt;enumeration value="Faroe Islands U21"/>
 *             &lt;enumeration value="Figueirense FC"/>
 *             &lt;enumeration value="Finland"/>
 *             &lt;enumeration value="Finland U21"/>
 *             &lt;enumeration value="Finn Harps FC"/>
 *             &lt;enumeration value="Flekkefjord"/>
 *             &lt;enumeration value="Flint"/>
 *             &lt;enumeration value="Flong/Hedehusene"/>
 *             &lt;enumeration value="Fluminense Rio Janeiro"/>
 *             &lt;enumeration value="Fram Reykjavik"/>
 *             &lt;enumeration value="France"/>
 *             &lt;enumeration value="France U20"/>
 *             &lt;enumeration value="France U21"/>
 *             &lt;enumeration value="Frederikshavn"/>
 *             &lt;enumeration value="Fremad Amager"/>
 *             &lt;enumeration value="Fulham"/>
 *             &lt;enumeration value="GAIS"/>
 *             &lt;enumeration value="Gabon"/>
 *             &lt;enumeration value="Gambia"/>
 *             &lt;enumeration value="Gefle IF"/>
 *             &lt;enumeration value="Georgia"/>
 *             &lt;enumeration value="Georgia U21"/>
 *             &lt;enumeration value="Germany U19"/>
 *             &lt;enumeration value="Germany U21"/>
 *             &lt;enumeration value="Ghana"/>
 *             &lt;enumeration value="Gillingham"/>
 *             &lt;enumeration value="Giravanz Kitakyushu"/>
 *             &lt;enumeration value="Goias EC"/>
 *             &lt;enumeration value="GrIFK Grankulla"/>
 *             &lt;enumeration value="Greece"/>
 *             &lt;enumeration value="Greece U19"/>
 *             &lt;enumeration value="Greece U21"/>
 *             &lt;enumeration value="Gremio FB Porto Alegrense"/>
 *             &lt;enumeration value="Guaratingueta Futebol"/>
 *             &lt;enumeration value="Gug B"/>
 *             &lt;enumeration value="Guinea"/>
 *             &lt;enumeration value="Habenhauser FV"/>
 *             &lt;enumeration value="Hadsund II"/>
 *             &lt;enumeration value="Haiti"/>
 *             &lt;enumeration value="Halmstads BK"/>
 *             &lt;enumeration value="Hamburger SV"/>
 *             &lt;enumeration value="Hammarby IF"/>
 *             &lt;enumeration value="Hannover 96"/>
 *             &lt;enumeration value="Hartlepool United"/>
 *             &lt;enumeration value="Heimdal"/>
 *             &lt;enumeration value="Hellerup IK"/>
 *             &lt;enumeration value="Helsingborgs IF"/>
 *             &lt;enumeration value="Herlev IF"/>
 *             &lt;enumeration value="Herlufsholm GF"/>
 *             &lt;enumeration value="Hertha BSC Berlin"/>
 *             &lt;enumeration value="Hjorring IF"/>
 *             &lt;enumeration value="Hobro"/>
 *             &lt;enumeration value="Honduras"/>
 *             &lt;enumeration value="Honefoss BK"/>
 *             &lt;enumeration value="Hradec Kralove U21"/>
 *             &lt;enumeration value="Huddersfield Town"/>
 *             &lt;enumeration value="Hull City AFC"/>
 *             &lt;enumeration value="Hungary"/>
 *             &lt;enumeration value="Hungary U21"/>
 *             &lt;enumeration value="IA Akranes"/>
 *             &lt;enumeration value="IF Brommapojkarna"/>
 *             &lt;enumeration value="IF Elfsborg"/>
 *             &lt;enumeration value="IF Foroyar"/>
 *             &lt;enumeration value="IF Skjold Birkerod"/>
 *             &lt;enumeration value="IFK Göteborg"/>
 *             &lt;enumeration value="IFK Norrköping"/>
 *             &lt;enumeration value="IK Brage Borlange"/>
 *             &lt;enumeration value="IK Start Kristiansand"/>
 *             &lt;enumeration value="Icasa"/>
 *             &lt;enumeration value="Iceland"/>
 *             &lt;enumeration value="Iceland U21"/>
 *             &lt;enumeration value="Ilves"/>
 *             &lt;enumeration value="Independiente Rivadavia"/>
 *             &lt;enumeration value="Indonesia"/>
 *             &lt;enumeration value="Ipswich Town FC"/>
 *             &lt;enumeration value="Iran"/>
 *             &lt;enumeration value="Iraq"/>
 *             &lt;enumeration value="Ireland"/>
 *             &lt;enumeration value="Ireland U21"/>
 *             &lt;enumeration value="Israel U21"/>
 *             &lt;enumeration value="Italy"/>
 *             &lt;enumeration value="Italy U21"/>
 *             &lt;enumeration value="Jaegersborg BK"/>
 *             &lt;enumeration value="Jamaica"/>
 *             &lt;enumeration value="Japan"/>
 *             &lt;enumeration value="Japs"/>
 *             &lt;enumeration value="Joinville EC"/>
 *             &lt;enumeration value="Jonkopings Sodra"/>
 *             &lt;enumeration value="KR Reykjavik"/>
 *             &lt;enumeration value="KaPa Helsinki"/>
 *             &lt;enumeration value="Kalmar FF"/>
 *             &lt;enumeration value="Kalundborg GB"/>
 *             &lt;enumeration value="Kazakhstan"/>
 *             &lt;enumeration value="Kazakhstan U21"/>
 *             &lt;enumeration value="Keflavik"/>
 *             &lt;enumeration value="Kenya"/>
 *             &lt;enumeration value="Kjellerup IF"/>
 *             &lt;enumeration value="Klubi 04"/>
 *             &lt;enumeration value="Koge"/>
 *             &lt;enumeration value="Kopparbergs/Göteborg (W)"/>
 *             &lt;enumeration value="Kuwait"/>
 *             &lt;enumeration value="Kyoto Purple Sanga"/>
 *             &lt;enumeration value="Latvia"/>
 *             &lt;enumeration value="Latvia U21"/>
 *             &lt;enumeration value="LdB FC Malmo (W)"/>
 *             &lt;enumeration value="Lebanon"/>
 *             &lt;enumeration value="Leeds United"/>
 *             &lt;enumeration value="Leicester City"/>
 *             &lt;enumeration value="Lesotho"/>
 *             &lt;enumeration value="Leyton Orient"/>
 *             &lt;enumeration value="Liberia"/>
 *             &lt;enumeration value="Libya"/>
 *             &lt;enumeration value="Liechtenstein"/>
 *             &lt;enumeration value="Liechtenstein U21"/>
 *             &lt;enumeration value="Lillestrom SK"/>
 *             &lt;enumeration value="Limerick FC"/>
 *             &lt;enumeration value="Lithuania"/>
 *             &lt;enumeration value="Lithuania U21"/>
 *             &lt;enumeration value="Liverpool"/>
 *             &lt;enumeration value="Ljungskile SK"/>
 *             &lt;enumeration value="Lolland Falster Alliancen"/>
 *             &lt;enumeration value="Longford Town"/>
 *             &lt;enumeration value="Lundtofte BK"/>
 *             &lt;enumeration value="Luxembourg"/>
 *             &lt;enumeration value="Luxembourg U21"/>
 *             &lt;enumeration value="Lyngby BK"/>
 *             &lt;enumeration value="Lystrup IF"/>
 *             &lt;enumeration value="MFK Karvina"/>
 *             &lt;enumeration value="Malawi"/>
 *             &lt;enumeration value="Mali"/>
 *             &lt;enumeration value="Malmö FF"/>
 *             &lt;enumeration value="Malta"/>
 *             &lt;enumeration value="Malta U21"/>
 *             &lt;enumeration value="Manchester City"/>
 *             &lt;enumeration value="Manchester United FC"/>
 *             &lt;enumeration value="Marienlyst"/>
 *             &lt;enumeration value="Mervue United FC"/>
 *             &lt;enumeration value="Mexico"/>
 *             &lt;enumeration value="Middlesbrough FC"/>
 *             &lt;enumeration value="Millwall"/>
 *             &lt;enumeration value="Milton Keynes Dons FC"/>
 *             &lt;enumeration value="Mjällby AIF"/>
 *             &lt;enumeration value="Mlada Boleslav U21"/>
 *             &lt;enumeration value="Molde FK"/>
 *             &lt;enumeration value="Molde FK 2"/>
 *             &lt;enumeration value="Moldova"/>
 *             &lt;enumeration value="Moldova U21"/>
 *             &lt;enumeration value="Montenegro"/>
 *             &lt;enumeration value="Montenegro U21"/>
 *             &lt;enumeration value="Morocco"/>
 *             &lt;enumeration value="Morud IF"/>
 *             &lt;enumeration value="Mozambique"/>
 *             &lt;enumeration value="NB Bornholm"/>
 *             &lt;enumeration value="Naestved Boldklub A/S"/>
 *             &lt;enumeration value="Namibia"/>
 *             &lt;enumeration value="Nautico Capibaribe"/>
 *             &lt;enumeration value="Netherlands"/>
 *             &lt;enumeration value="Netherlands U19"/>
 *             &lt;enumeration value="Netherlands U21"/>
 *             &lt;enumeration value="Newcastle United FC"/>
 *             &lt;enumeration value="Newell's Old Boys"/>
 *             &lt;enumeration value="Niger"/>
 *             &lt;enumeration value="Nigeria"/>
 *             &lt;enumeration value="Nordvestmors BK"/>
 *             &lt;enumeration value="Northampton Town"/>
 *             &lt;enumeration value="Northern Ireland U21"/>
 *             &lt;enumeration value="Norway"/>
 *             &lt;enumeration value="Norway U19"/>
 *             &lt;enumeration value="Norway U21"/>
 *             &lt;enumeration value="Norwich City FC"/>
 *             &lt;enumeration value="Nottingham Forest"/>
 *             &lt;enumeration value="Notts County"/>
 *             &lt;enumeration value="Næsby BK"/>
 *             &lt;enumeration value="Næstved IF"/>
 *             &lt;enumeration value="OB Odense"/>
 *             &lt;enumeration value="OSC Bremerhaven"/>
 *             &lt;enumeration value="Odd Grenland Skien"/>
 *             &lt;enumeration value="Oeste Itapolis"/>
 *             &lt;enumeration value="Oldham Athletic"/>
 *             &lt;enumeration value="Olimpo"/>
 *             &lt;enumeration value="Oman"/>
 *             &lt;enumeration value="Orgryte IS"/>
 *             &lt;enumeration value="Osters IF Vaxjo"/>
 *             &lt;enumeration value="Ostersunds FK"/>
 *             &lt;enumeration value="Otterup B og IK"/>
 *             &lt;enumeration value="Oulun Palloseura jalkapallo"/>
 *             &lt;enumeration value="PFK Kryliya Sovetov Samara"/>
 *             &lt;enumeration value="POHU"/>
 *             &lt;enumeration value="Panama"/>
 *             &lt;enumeration value="Paraguay"/>
 *             &lt;enumeration value="Paraná Clube"/>
 *             &lt;enumeration value="Pardubice"/>
 *             &lt;enumeration value="Paysandu"/>
 *             &lt;enumeration value="Persidafon"/>
 *             &lt;enumeration value="Persisam Putra Samarinda"/>
 *             &lt;enumeration value="Peru"/>
 *             &lt;enumeration value="Peterborough United"/>
 *             &lt;enumeration value="Philadelphia Union"/>
 *             &lt;enumeration value="Pitea IF"/>
 *             &lt;enumeration value="Poland"/>
 *             &lt;enumeration value="Poland U19"/>
 *             &lt;enumeration value="Poland U21"/>
 *             &lt;enumeration value="Port Vale"/>
 *             &lt;enumeration value="Portsmouth"/>
 *             &lt;enumeration value="Portugal"/>
 *             &lt;enumeration value="Portugal U19"/>
 *             &lt;enumeration value="Portugal U21"/>
 *             &lt;enumeration value="Portuguesa SP"/>
 *             &lt;enumeration value="Preston North End FC"/>
 *             &lt;enumeration value="Qatar"/>
 *             &lt;enumeration value="Queens Park Rangers FC"/>
 *             &lt;enumeration value="Randers FC"/>
 *             &lt;enumeration value="Reading"/>
 *             &lt;enumeration value="Republic of Korea"/>
 *             &lt;enumeration value="Ringkøbing IF"/>
 *             &lt;enumeration value="Romania"/>
 *             &lt;enumeration value="Romania U21"/>
 *             &lt;enumeration value="Romsås"/>
 *             &lt;enumeration value="Rosenborg BK"/>
 *             &lt;enumeration value="Rot-Weiss Ahlen"/>
 *             &lt;enumeration value="Rotherham United FC"/>
 *             &lt;enumeration value="Russia"/>
 *             &lt;enumeration value="Russia U21"/>
 *             &lt;enumeration value="Rwanda"/>
 *             &lt;enumeration value="SC Freiburg"/>
 *             &lt;enumeration value="SC Internacional PA"/>
 *             &lt;enumeration value="SFC Opava"/>
 *             &lt;enumeration value="SK Brann Bergen"/>
 *             &lt;enumeration value="SK Slovan Varnsdorf"/>
 *             &lt;enumeration value="SV Elversberg"/>
 *             &lt;enumeration value="SV Werder Bremen"/>
 *             &lt;enumeration value="Saedding/Guldager IF"/>
 *             &lt;enumeration value="SalPa Salo"/>
 *             &lt;enumeration value="Salthill Devon"/>
 *             &lt;enumeration value="San Marino U21"/>
 *             &lt;enumeration value="San Martin de San Juan"/>
 *             &lt;enumeration value="Sandnes Ulf"/>
 *             &lt;enumeration value="Santos FC "/>
 *             &lt;enumeration value="Sarpsborg 08"/>
 *             &lt;enumeration value="Schwachhausen"/>
 *             &lt;enumeration value="Scotland"/>
 *             &lt;enumeration value="Scotland U21"/>
 *             &lt;enumeration value="Scunthorpe United"/>
 *             &lt;enumeration value="Senegal"/>
 *             &lt;enumeration value="Serbia"/>
 *             &lt;enumeration value="Serbia U21"/>
 *             &lt;enumeration value="Shamrock Rovers"/>
 *             &lt;enumeration value="Sheffield United FC"/>
 *             &lt;enumeration value="Sheffield Wednesday FC"/>
 *             &lt;enumeration value="Shelbourne FC"/>
 *             &lt;enumeration value="Shrewsbury Town"/>
 *             &lt;enumeration value="Sierra Leone"/>
 *             &lt;enumeration value="Sigma Olomouc U21"/>
 *             &lt;enumeration value="Silkeborg IF"/>
 *             &lt;enumeration value="Skive IF"/>
 *             &lt;enumeration value="Skovbakken"/>
 *             &lt;enumeration value="Skovshoved"/>
 *             &lt;enumeration value="Sligo Rovers FC"/>
 *             &lt;enumeration value="Slovacko U21"/>
 *             &lt;enumeration value="Slovakia"/>
 *             &lt;enumeration value="Slovakia U21"/>
 *             &lt;enumeration value="Slovenia"/>
 *             &lt;enumeration value="Slovenia U21"/>
 *             &lt;enumeration value="Sociedade Esportiva Palmeiras"/>
 *             &lt;enumeration value="Sogndal IL"/>
 *             &lt;enumeration value="Sohus Stige"/>
 *             &lt;enumeration value="SonderjyskE"/>
 *             &lt;enumeration value="South Africa"/>
 *             &lt;enumeration value="South Korea U20"/>
 *             &lt;enumeration value="Southampton FC"/>
 *             &lt;enumeration value="Spain"/>
 *             &lt;enumeration value="Spain U19"/>
 *             &lt;enumeration value="Spain U21"/>
 *             &lt;enumeration value="Sport Recife"/>
 *             &lt;enumeration value="St Patricks Athletic FC"/>
 *             &lt;enumeration value="Stevenage Borough"/>
 *             &lt;enumeration value="Stjarnan Gardabaer"/>
 *             &lt;enumeration value="Stoke City FC"/>
 *             &lt;enumeration value="Stromsgodset IF"/>
 *             &lt;enumeration value="Stromsgodset IF II"/>
 *             &lt;enumeration value="Sudan"/>
 *             &lt;enumeration value="Sunderland"/>
 *             &lt;enumeration value="Svebolle BI"/>
 *             &lt;enumeration value="Svendborg"/>
 *             &lt;enumeration value="Swansea City"/>
 *             &lt;enumeration value="Sweden"/>
 *             &lt;enumeration value="Sweden U21"/>
 *             &lt;enumeration value="Swindon Town"/>
 *             &lt;enumeration value="Switzerland"/>
 *             &lt;enumeration value="Switzerland U21"/>
 *             &lt;enumeration value="Sydalliancen 2007"/>
 *             &lt;enumeration value="Sydvest"/>
 *             &lt;enumeration value="Syrianska Föreningen FC"/>
 *             &lt;enumeration value="São Paulo FC"/>
 *             &lt;enumeration value="TPV Tampere"/>
 *             &lt;enumeration value="TSV 1860 Munchen II"/>
 *             &lt;enumeration value="TSV Eintracht Braunschweig"/>
 *             &lt;enumeration value="Tahiti"/>
 *             &lt;enumeration value="Tanzania"/>
 *             &lt;enumeration value="Tarnby BK"/>
 *             &lt;enumeration value="Teplice U21"/>
 *             &lt;enumeration value="Thisted FC"/>
 *             &lt;enumeration value="Thor Akureyri"/>
 *             &lt;enumeration value="Tigre"/>
 *             &lt;enumeration value="Tjorring IF"/>
 *             &lt;enumeration value="Togo"/>
 *             &lt;enumeration value="Tottenham Hotspur"/>
 *             &lt;enumeration value="Tranmere Rovers"/>
 *             &lt;enumeration value="Trinidad And Tobago"/>
 *             &lt;enumeration value="Tromso IL"/>
 *             &lt;enumeration value="Træff"/>
 *             &lt;enumeration value="Tunisia"/>
 *             &lt;enumeration value="Turkey U21"/>
 *             &lt;enumeration value="Turkspor Bremen"/>
 *             &lt;enumeration value="Tuse"/>
 *             &lt;enumeration value="Tved"/>
 *             &lt;enumeration value="USA"/>
 *             &lt;enumeration value="Ubberud IF"/>
 *             &lt;enumeration value="Uganda"/>
 *             &lt;enumeration value="Ukraine"/>
 *             &lt;enumeration value="Ukraine U21"/>
 *             &lt;enumeration value="Union Bremen"/>
 *             &lt;enumeration value="University College Dublin FC"/>
 *             &lt;enumeration value="Uruguay"/>
 *             &lt;enumeration value="Uzbekistan"/>
 *             &lt;enumeration value="Valerenga IF Oslo"/>
 *             &lt;enumeration value="Vallensbaek IF"/>
 *             &lt;enumeration value="Valur Reykjavik"/>
 *             &lt;enumeration value="Vanlose"/>
 *             &lt;enumeration value="Varbergs BoIS FC"/>
 *             &lt;enumeration value="Varde"/>
 *             &lt;enumeration value="Vatanspor/VRI"/>
 *             &lt;enumeration value="Vejle"/>
 *             &lt;enumeration value="Venezuela"/>
 *             &lt;enumeration value="VfB Stuttgart"/>
 *             &lt;enumeration value="VfL Wolfsburg"/>
 *             &lt;enumeration value="Viborg FF"/>
 *             &lt;enumeration value="Vigor"/>
 *             &lt;enumeration value="Viking Stavanger"/>
 *             &lt;enumeration value="Vikingur Olafsvik"/>
 *             &lt;enumeration value="Wales U21"/>
 *             &lt;enumeration value="Walsall"/>
 *             &lt;enumeration value="Waterford United"/>
 *             &lt;enumeration value="Watford FC"/>
 *             &lt;enumeration value="Werder Bremen III"/>
 *             &lt;enumeration value="West Bromwich Albion FC"/>
 *             &lt;enumeration value="West Ham United"/>
 *             &lt;enumeration value="Westfalia Herne"/>
 *             &lt;enumeration value="Wexford Youths FC"/>
 *             &lt;enumeration value="Wigan Athletic"/>
 *             &lt;enumeration value="Wolverhampton Wanderers"/>
 *             &lt;enumeration value="Wulsdorf"/>
 *             &lt;enumeration value="Yeovil Town"/>
 *             &lt;enumeration value="Zambia"/>
 *             &lt;enumeration value="Zimbabwe"/>
 *             &lt;enumeration value="Znojmo"/>
 *             &lt;enumeration value="Åtvidabergs FF"/>
 *             &lt;enumeration value="ØIF"/>
 *             &lt;enumeration value="Østerbro IF"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="id" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *             &lt;enumeration value="1"/>
 *             &lt;enumeration value="10"/>
 *             &lt;enumeration value="100351"/>
 *             &lt;enumeration value="100352"/>
 *             &lt;enumeration value="100414"/>
 *             &lt;enumeration value="100600"/>
 *             &lt;enumeration value="100601"/>
 *             &lt;enumeration value="100838"/>
 *             &lt;enumeration value="101"/>
 *             &lt;enumeration value="102"/>
 *             &lt;enumeration value="1039"/>
 *             &lt;enumeration value="1040"/>
 *             &lt;enumeration value="1041"/>
 *             &lt;enumeration value="1042"/>
 *             &lt;enumeration value="1045"/>
 *             &lt;enumeration value="1046"/>
 *             &lt;enumeration value="1047"/>
 *             &lt;enumeration value="1049"/>
 *             &lt;enumeration value="105"/>
 *             &lt;enumeration value="1050"/>
 *             &lt;enumeration value="1056"/>
 *             &lt;enumeration value="106"/>
 *             &lt;enumeration value="1061"/>
 *             &lt;enumeration value="1063"/>
 *             &lt;enumeration value="108"/>
 *             &lt;enumeration value="11"/>
 *             &lt;enumeration value="1107"/>
 *             &lt;enumeration value="1110"/>
 *             &lt;enumeration value="1126"/>
 *             &lt;enumeration value="1131"/>
 *             &lt;enumeration value="1132"/>
 *             &lt;enumeration value="1152"/>
 *             &lt;enumeration value="11551"/>
 *             &lt;enumeration value="12"/>
 *             &lt;enumeration value="1221"/>
 *             &lt;enumeration value="1223"/>
 *             &lt;enumeration value="126372"/>
 *             &lt;enumeration value="126375"/>
 *             &lt;enumeration value="13"/>
 *             &lt;enumeration value="131"/>
 *             &lt;enumeration value="132"/>
 *             &lt;enumeration value="1322"/>
 *             &lt;enumeration value="13260"/>
 *             &lt;enumeration value="13265"/>
 *             &lt;enumeration value="133"/>
 *             &lt;enumeration value="1338"/>
 *             &lt;enumeration value="134"/>
 *             &lt;enumeration value="135"/>
 *             &lt;enumeration value="1359"/>
 *             &lt;enumeration value="1364"/>
 *             &lt;enumeration value="1365"/>
 *             &lt;enumeration value="1366"/>
 *             &lt;enumeration value="1367"/>
 *             &lt;enumeration value="1368"/>
 *             &lt;enumeration value="137"/>
 *             &lt;enumeration value="1374"/>
 *             &lt;enumeration value="1377"/>
 *             &lt;enumeration value="13777"/>
 *             &lt;enumeration value="13778"/>
 *             &lt;enumeration value="1378"/>
 *             &lt;enumeration value="13783"/>
 *             &lt;enumeration value="13785"/>
 *             &lt;enumeration value="13787"/>
 *             &lt;enumeration value="13788"/>
 *             &lt;enumeration value="13790"/>
 *             &lt;enumeration value="138"/>
 *             &lt;enumeration value="1380"/>
 *             &lt;enumeration value="1382"/>
 *             &lt;enumeration value="1384"/>
 *             &lt;enumeration value="1385"/>
 *             &lt;enumeration value="1388"/>
 *             &lt;enumeration value="1389"/>
 *             &lt;enumeration value="139"/>
 *             &lt;enumeration value="1391"/>
 *             &lt;enumeration value="1392"/>
 *             &lt;enumeration value="1395"/>
 *             &lt;enumeration value="1397"/>
 *             &lt;enumeration value="14"/>
 *             &lt;enumeration value="140"/>
 *             &lt;enumeration value="1402"/>
 *             &lt;enumeration value="1403"/>
 *             &lt;enumeration value="1404"/>
 *             &lt;enumeration value="141"/>
 *             &lt;enumeration value="142"/>
 *             &lt;enumeration value="143"/>
 *             &lt;enumeration value="143138"/>
 *             &lt;enumeration value="143141"/>
 *             &lt;enumeration value="143446"/>
 *             &lt;enumeration value="144"/>
 *             &lt;enumeration value="146"/>
 *             &lt;enumeration value="147"/>
 *             &lt;enumeration value="1477"/>
 *             &lt;enumeration value="15"/>
 *             &lt;enumeration value="150"/>
 *             &lt;enumeration value="1505"/>
 *             &lt;enumeration value="1506"/>
 *             &lt;enumeration value="151"/>
 *             &lt;enumeration value="1515"/>
 *             &lt;enumeration value="152"/>
 *             &lt;enumeration value="1524"/>
 *             &lt;enumeration value="1525"/>
 *             &lt;enumeration value="1526"/>
 *             &lt;enumeration value="1528"/>
 *             &lt;enumeration value="1529"/>
 *             &lt;enumeration value="153"/>
 *             &lt;enumeration value="1533"/>
 *             &lt;enumeration value="156"/>
 *             &lt;enumeration value="157"/>
 *             &lt;enumeration value="158063"/>
 *             &lt;enumeration value="16"/>
 *             &lt;enumeration value="1649"/>
 *             &lt;enumeration value="16648"/>
 *             &lt;enumeration value="16654"/>
 *             &lt;enumeration value="16665"/>
 *             &lt;enumeration value="16900"/>
 *             &lt;enumeration value="17"/>
 *             &lt;enumeration value="177022"/>
 *             &lt;enumeration value="18"/>
 *             &lt;enumeration value="1848"/>
 *             &lt;enumeration value="19"/>
 *             &lt;enumeration value="1909"/>
 *             &lt;enumeration value="1928"/>
 *             &lt;enumeration value="1929"/>
 *             &lt;enumeration value="1930"/>
 *             &lt;enumeration value="1931"/>
 *             &lt;enumeration value="1934"/>
 *             &lt;enumeration value="1935"/>
 *             &lt;enumeration value="1936"/>
 *             &lt;enumeration value="19415"/>
 *             &lt;enumeration value="19420"/>
 *             &lt;enumeration value="19421"/>
 *             &lt;enumeration value="19422"/>
 *             &lt;enumeration value="19423"/>
 *             &lt;enumeration value="19424"/>
 *             &lt;enumeration value="19425"/>
 *             &lt;enumeration value="19426"/>
 *             &lt;enumeration value="19427"/>
 *             &lt;enumeration value="19429"/>
 *             &lt;enumeration value="19430"/>
 *             &lt;enumeration value="19431"/>
 *             &lt;enumeration value="19432"/>
 *             &lt;enumeration value="19433"/>
 *             &lt;enumeration value="19434"/>
 *             &lt;enumeration value="19436"/>
 *             &lt;enumeration value="19437"/>
 *             &lt;enumeration value="19445"/>
 *             &lt;enumeration value="19446"/>
 *             &lt;enumeration value="19447"/>
 *             &lt;enumeration value="19448"/>
 *             &lt;enumeration value="19449"/>
 *             &lt;enumeration value="19450"/>
 *             &lt;enumeration value="19497"/>
 *             &lt;enumeration value="19513"/>
 *             &lt;enumeration value="19514"/>
 *             &lt;enumeration value="196236"/>
 *             &lt;enumeration value="19628"/>
 *             &lt;enumeration value="19691"/>
 *             &lt;enumeration value="19693"/>
 *             &lt;enumeration value="197"/>
 *             &lt;enumeration value="19703"/>
 *             &lt;enumeration value="19704"/>
 *             &lt;enumeration value="19705"/>
 *             &lt;enumeration value="19706"/>
 *             &lt;enumeration value="19707"/>
 *             &lt;enumeration value="19791"/>
 *             &lt;enumeration value="19821"/>
 *             &lt;enumeration value="19822"/>
 *             &lt;enumeration value="19831"/>
 *             &lt;enumeration value="19836"/>
 *             &lt;enumeration value="19851"/>
 *             &lt;enumeration value="19858"/>
 *             &lt;enumeration value="19953"/>
 *             &lt;enumeration value="19958"/>
 *             &lt;enumeration value="19960"/>
 *             &lt;enumeration value="2"/>
 *             &lt;enumeration value="20"/>
 *             &lt;enumeration value="200"/>
 *             &lt;enumeration value="2013"/>
 *             &lt;enumeration value="2014"/>
 *             &lt;enumeration value="2015"/>
 *             &lt;enumeration value="2035"/>
 *             &lt;enumeration value="208"/>
 *             &lt;enumeration value="210"/>
 *             &lt;enumeration value="2102"/>
 *             &lt;enumeration value="2103"/>
 *             &lt;enumeration value="2107"/>
 *             &lt;enumeration value="22"/>
 *             &lt;enumeration value="2225"/>
 *             &lt;enumeration value="2226"/>
 *             &lt;enumeration value="2244"/>
 *             &lt;enumeration value="2260"/>
 *             &lt;enumeration value="2263"/>
 *             &lt;enumeration value="22698"/>
 *             &lt;enumeration value="22864"/>
 *             &lt;enumeration value="22871"/>
 *             &lt;enumeration value="22872"/>
 *             &lt;enumeration value="22873"/>
 *             &lt;enumeration value="22874"/>
 *             &lt;enumeration value="22875"/>
 *             &lt;enumeration value="22876"/>
 *             &lt;enumeration value="22877"/>
 *             &lt;enumeration value="22878"/>
 *             &lt;enumeration value="22879"/>
 *             &lt;enumeration value="22880"/>
 *             &lt;enumeration value="22881"/>
 *             &lt;enumeration value="22882"/>
 *             &lt;enumeration value="22883"/>
 *             &lt;enumeration value="22884"/>
 *             &lt;enumeration value="22885"/>
 *             &lt;enumeration value="22886"/>
 *             &lt;enumeration value="22887"/>
 *             &lt;enumeration value="22904"/>
 *             &lt;enumeration value="23"/>
 *             &lt;enumeration value="23119"/>
 *             &lt;enumeration value="23189"/>
 *             &lt;enumeration value="23364"/>
 *             &lt;enumeration value="24"/>
 *             &lt;enumeration value="247495"/>
 *             &lt;enumeration value="252736"/>
 *             &lt;enumeration value="253083"/>
 *             &lt;enumeration value="253100"/>
 *             &lt;enumeration value="253102"/>
 *             &lt;enumeration value="254943"/>
 *             &lt;enumeration value="255758"/>
 *             &lt;enumeration value="26"/>
 *             &lt;enumeration value="269"/>
 *             &lt;enumeration value="27"/>
 *             &lt;enumeration value="270"/>
 *             &lt;enumeration value="28"/>
 *             &lt;enumeration value="280"/>
 *             &lt;enumeration value="281096"/>
 *             &lt;enumeration value="283"/>
 *             &lt;enumeration value="284"/>
 *             &lt;enumeration value="291459"/>
 *             &lt;enumeration value="3"/>
 *             &lt;enumeration value="30"/>
 *             &lt;enumeration value="312388"/>
 *             &lt;enumeration value="323"/>
 *             &lt;enumeration value="324"/>
 *             &lt;enumeration value="325"/>
 *             &lt;enumeration value="326"/>
 *             &lt;enumeration value="327"/>
 *             &lt;enumeration value="33"/>
 *             &lt;enumeration value="331"/>
 *             &lt;enumeration value="332"/>
 *             &lt;enumeration value="332331"/>
 *             &lt;enumeration value="332332"/>
 *             &lt;enumeration value="332436"/>
 *             &lt;enumeration value="332438"/>
 *             &lt;enumeration value="332440"/>
 *             &lt;enumeration value="332441"/>
 *             &lt;enumeration value="332442"/>
 *             &lt;enumeration value="332444"/>
 *             &lt;enumeration value="332446"/>
 *             &lt;enumeration value="333"/>
 *             &lt;enumeration value="334"/>
 *             &lt;enumeration value="335"/>
 *             &lt;enumeration value="336"/>
 *             &lt;enumeration value="337"/>
 *             &lt;enumeration value="338"/>
 *             &lt;enumeration value="34"/>
 *             &lt;enumeration value="340487"/>
 *             &lt;enumeration value="3437"/>
 *             &lt;enumeration value="3442"/>
 *             &lt;enumeration value="3553"/>
 *             &lt;enumeration value="356648"/>
 *             &lt;enumeration value="361155"/>
 *             &lt;enumeration value="361173"/>
 *             &lt;enumeration value="36206"/>
 *             &lt;enumeration value="363546"/>
 *             &lt;enumeration value="367"/>
 *             &lt;enumeration value="369"/>
 *             &lt;enumeration value="37"/>
 *             &lt;enumeration value="370"/>
 *             &lt;enumeration value="371"/>
 *             &lt;enumeration value="372"/>
 *             &lt;enumeration value="372746"/>
 *             &lt;enumeration value="373"/>
 *             &lt;enumeration value="374"/>
 *             &lt;enumeration value="375"/>
 *             &lt;enumeration value="378"/>
 *             &lt;enumeration value="3792"/>
 *             &lt;enumeration value="3793"/>
 *             &lt;enumeration value="3795"/>
 *             &lt;enumeration value="3796"/>
 *             &lt;enumeration value="3797"/>
 *             &lt;enumeration value="3798"/>
 *             &lt;enumeration value="38"/>
 *             &lt;enumeration value="3800"/>
 *             &lt;enumeration value="3801"/>
 *             &lt;enumeration value="3802"/>
 *             &lt;enumeration value="3803"/>
 *             &lt;enumeration value="3805"/>
 *             &lt;enumeration value="3806"/>
 *             &lt;enumeration value="3808"/>
 *             &lt;enumeration value="381"/>
 *             &lt;enumeration value="381387"/>
 *             &lt;enumeration value="3814"/>
 *             &lt;enumeration value="3815"/>
 *             &lt;enumeration value="3819"/>
 *             &lt;enumeration value="3835"/>
 *             &lt;enumeration value="3836"/>
 *             &lt;enumeration value="3837"/>
 *             &lt;enumeration value="385"/>
 *             &lt;enumeration value="387"/>
 *             &lt;enumeration value="388"/>
 *             &lt;enumeration value="39"/>
 *             &lt;enumeration value="3903"/>
 *             &lt;enumeration value="391329"/>
 *             &lt;enumeration value="393572"/>
 *             &lt;enumeration value="3941"/>
 *             &lt;enumeration value="4"/>
 *             &lt;enumeration value="40"/>
 *             &lt;enumeration value="4073"/>
 *             &lt;enumeration value="41"/>
 *             &lt;enumeration value="411877"/>
 *             &lt;enumeration value="411887"/>
 *             &lt;enumeration value="411896"/>
 *             &lt;enumeration value="417027"/>
 *             &lt;enumeration value="419003"/>
 *             &lt;enumeration value="419346"/>
 *             &lt;enumeration value="42"/>
 *             &lt;enumeration value="427639"/>
 *             &lt;enumeration value="43"/>
 *             &lt;enumeration value="44"/>
 *             &lt;enumeration value="45"/>
 *             &lt;enumeration value="45128"/>
 *             &lt;enumeration value="45214"/>
 *             &lt;enumeration value="45389"/>
 *             &lt;enumeration value="46"/>
 *             &lt;enumeration value="460516"/>
 *             &lt;enumeration value="471"/>
 *             &lt;enumeration value="48"/>
 *             &lt;enumeration value="48779"/>
 *             &lt;enumeration value="489027"/>
 *             &lt;enumeration value="49"/>
 *             &lt;enumeration value="490"/>
 *             &lt;enumeration value="490144"/>
 *             &lt;enumeration value="491"/>
 *             &lt;enumeration value="5"/>
 *             &lt;enumeration value="50"/>
 *             &lt;enumeration value="50669"/>
 *             &lt;enumeration value="51"/>
 *             &lt;enumeration value="51078"/>
 *             &lt;enumeration value="5169"/>
 *             &lt;enumeration value="5183"/>
 *             &lt;enumeration value="5185"/>
 *             &lt;enumeration value="5194"/>
 *             &lt;enumeration value="52"/>
 *             &lt;enumeration value="5203"/>
 *             &lt;enumeration value="5204"/>
 *             &lt;enumeration value="525"/>
 *             &lt;enumeration value="52710"/>
 *             &lt;enumeration value="53"/>
 *             &lt;enumeration value="54"/>
 *             &lt;enumeration value="5449"/>
 *             &lt;enumeration value="5452"/>
 *             &lt;enumeration value="5463"/>
 *             &lt;enumeration value="5471"/>
 *             &lt;enumeration value="5494"/>
 *             &lt;enumeration value="55"/>
 *             &lt;enumeration value="550"/>
 *             &lt;enumeration value="553"/>
 *             &lt;enumeration value="554"/>
 *             &lt;enumeration value="556"/>
 *             &lt;enumeration value="558"/>
 *             &lt;enumeration value="56"/>
 *             &lt;enumeration value="5608"/>
 *             &lt;enumeration value="563"/>
 *             &lt;enumeration value="564"/>
 *             &lt;enumeration value="5644"/>
 *             &lt;enumeration value="566"/>
 *             &lt;enumeration value="5668"/>
 *             &lt;enumeration value="568"/>
 *             &lt;enumeration value="569"/>
 *             &lt;enumeration value="5690"/>
 *             &lt;enumeration value="570"/>
 *             &lt;enumeration value="5723"/>
 *             &lt;enumeration value="573"/>
 *             &lt;enumeration value="5761"/>
 *             &lt;enumeration value="5762"/>
 *             &lt;enumeration value="5764"/>
 *             &lt;enumeration value="576879"/>
 *             &lt;enumeration value="5773"/>
 *             &lt;enumeration value="58"/>
 *             &lt;enumeration value="582"/>
 *             &lt;enumeration value="58213"/>
 *             &lt;enumeration value="588673"/>
 *             &lt;enumeration value="589111"/>
 *             &lt;enumeration value="59"/>
 *             &lt;enumeration value="592499"/>
 *             &lt;enumeration value="595289"/>
 *             &lt;enumeration value="595334"/>
 *             &lt;enumeration value="6"/>
 *             &lt;enumeration value="60"/>
 *             &lt;enumeration value="602174"/>
 *             &lt;enumeration value="602178"/>
 *             &lt;enumeration value="602290"/>
 *             &lt;enumeration value="602291"/>
 *             &lt;enumeration value="602293"/>
 *             &lt;enumeration value="61"/>
 *             &lt;enumeration value="6101"/>
 *             &lt;enumeration value="61306"/>
 *             &lt;enumeration value="614888"/>
 *             &lt;enumeration value="617"/>
 *             &lt;enumeration value="61863"/>
 *             &lt;enumeration value="62"/>
 *             &lt;enumeration value="62412"/>
 *             &lt;enumeration value="62502"/>
 *             &lt;enumeration value="62524"/>
 *             &lt;enumeration value="62544"/>
 *             &lt;enumeration value="63"/>
 *             &lt;enumeration value="631"/>
 *             &lt;enumeration value="63419"/>
 *             &lt;enumeration value="63456"/>
 *             &lt;enumeration value="63457"/>
 *             &lt;enumeration value="63459"/>
 *             &lt;enumeration value="636"/>
 *             &lt;enumeration value="64"/>
 *             &lt;enumeration value="65"/>
 *             &lt;enumeration value="653"/>
 *             &lt;enumeration value="658"/>
 *             &lt;enumeration value="65897"/>
 *             &lt;enumeration value="65946"/>
 *             &lt;enumeration value="65947"/>
 *             &lt;enumeration value="66"/>
 *             &lt;enumeration value="661497"/>
 *             &lt;enumeration value="673"/>
 *             &lt;enumeration value="6759"/>
 *             &lt;enumeration value="68"/>
 *             &lt;enumeration value="68332"/>
 *             &lt;enumeration value="68333"/>
 *             &lt;enumeration value="69"/>
 *             &lt;enumeration value="692"/>
 *             &lt;enumeration value="699215"/>
 *             &lt;enumeration value="699217"/>
 *             &lt;enumeration value="7"/>
 *             &lt;enumeration value="7051"/>
 *             &lt;enumeration value="71"/>
 *             &lt;enumeration value="73"/>
 *             &lt;enumeration value="73855"/>
 *             &lt;enumeration value="739793"/>
 *             &lt;enumeration value="739794"/>
 *             &lt;enumeration value="739795"/>
 *             &lt;enumeration value="739796"/>
 *             &lt;enumeration value="739797"/>
 *             &lt;enumeration value="739798"/>
 *             &lt;enumeration value="739799"/>
 *             &lt;enumeration value="739800"/>
 *             &lt;enumeration value="739801"/>
 *             &lt;enumeration value="739803"/>
 *             &lt;enumeration value="739804"/>
 *             &lt;enumeration value="739805"/>
 *             &lt;enumeration value="739806"/>
 *             &lt;enumeration value="74"/>
 *             &lt;enumeration value="74415"/>
 *             &lt;enumeration value="748337"/>
 *             &lt;enumeration value="748338"/>
 *             &lt;enumeration value="74853"/>
 *             &lt;enumeration value="74854"/>
 *             &lt;enumeration value="75092"/>
 *             &lt;enumeration value="755"/>
 *             &lt;enumeration value="75531"/>
 *             &lt;enumeration value="756"/>
 *             &lt;enumeration value="758"/>
 *             &lt;enumeration value="76"/>
 *             &lt;enumeration value="761"/>
 *             &lt;enumeration value="762"/>
 *             &lt;enumeration value="763"/>
 *             &lt;enumeration value="764"/>
 *             &lt;enumeration value="765"/>
 *             &lt;enumeration value="766"/>
 *             &lt;enumeration value="767"/>
 *             &lt;enumeration value="768"/>
 *             &lt;enumeration value="769"/>
 *             &lt;enumeration value="77"/>
 *             &lt;enumeration value="770"/>
 *             &lt;enumeration value="772"/>
 *             &lt;enumeration value="773"/>
 *             &lt;enumeration value="774"/>
 *             &lt;enumeration value="775"/>
 *             &lt;enumeration value="776"/>
 *             &lt;enumeration value="777"/>
 *             &lt;enumeration value="778"/>
 *             &lt;enumeration value="77833"/>
 *             &lt;enumeration value="77834"/>
 *             &lt;enumeration value="779"/>
 *             &lt;enumeration value="77961"/>
 *             &lt;enumeration value="78"/>
 *             &lt;enumeration value="780"/>
 *             &lt;enumeration value="781"/>
 *             &lt;enumeration value="782"/>
 *             &lt;enumeration value="783"/>
 *             &lt;enumeration value="78382"/>
 *             &lt;enumeration value="784"/>
 *             &lt;enumeration value="785"/>
 *             &lt;enumeration value="786"/>
 *             &lt;enumeration value="788"/>
 *             &lt;enumeration value="789"/>
 *             &lt;enumeration value="790"/>
 *             &lt;enumeration value="792"/>
 *             &lt;enumeration value="793"/>
 *             &lt;enumeration value="794"/>
 *             &lt;enumeration value="795"/>
 *             &lt;enumeration value="797"/>
 *             &lt;enumeration value="8"/>
 *             &lt;enumeration value="80"/>
 *             &lt;enumeration value="81"/>
 *             &lt;enumeration value="818510"/>
 *             &lt;enumeration value="819710"/>
 *             &lt;enumeration value="819711"/>
 *             &lt;enumeration value="819737"/>
 *             &lt;enumeration value="82"/>
 *             &lt;enumeration value="823"/>
 *             &lt;enumeration value="824"/>
 *             &lt;enumeration value="825"/>
 *             &lt;enumeration value="82618"/>
 *             &lt;enumeration value="8272"/>
 *             &lt;enumeration value="83"/>
 *             &lt;enumeration value="8321"/>
 *             &lt;enumeration value="84"/>
 *             &lt;enumeration value="842"/>
 *             &lt;enumeration value="854604"/>
 *             &lt;enumeration value="854605"/>
 *             &lt;enumeration value="854606"/>
 *             &lt;enumeration value="854608"/>
 *             &lt;enumeration value="854609"/>
 *             &lt;enumeration value="854611"/>
 *             &lt;enumeration value="854612"/>
 *             &lt;enumeration value="854613"/>
 *             &lt;enumeration value="87209"/>
 *             &lt;enumeration value="87723"/>
 *             &lt;enumeration value="87729"/>
 *             &lt;enumeration value="8790"/>
 *             &lt;enumeration value="8795"/>
 *             &lt;enumeration value="879948"/>
 *             &lt;enumeration value="88"/>
 *             &lt;enumeration value="8843"/>
 *             &lt;enumeration value="89"/>
 *             &lt;enumeration value="89114"/>
 *             &lt;enumeration value="89376"/>
 *             &lt;enumeration value="9"/>
 *             &lt;enumeration value="903"/>
 *             &lt;enumeration value="903475"/>
 *             &lt;enumeration value="91946"/>
 *             &lt;enumeration value="921999"/>
 *             &lt;enumeration value="9245"/>
 *             &lt;enumeration value="9247"/>
 *             &lt;enumeration value="9365"/>
 *             &lt;enumeration value="94530"/>
 *             &lt;enumeration value="95"/>
 *             &lt;enumeration value="95712"/>
 *             &lt;enumeration value="96"/>
 *             &lt;enumeration value="96110"/>
 *             &lt;enumeration value="962"/>
 *             &lt;enumeration value="96252"/>
 *             &lt;enumeration value="9692"/>
 *             &lt;enumeration value="97"/>
 *             &lt;enumeration value="977"/>
 *             &lt;enumeration value="982"/>
 *             &lt;enumeration value="984"/>
 *             &lt;enumeration value="985"/>
 *             &lt;enumeration value="986"/>
 *             &lt;enumeration value="988"/>
 *             &lt;enumeration value="989"/>
 *             &lt;enumeration value="990"/>
 *             &lt;enumeration value="991"/>
 *             &lt;enumeration value="992"/>
 *             &lt;enumeration value="993"/>
 *             &lt;enumeration value="995"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "Participant")
public class Participant {

    @XmlAttribute(name = "type")
    protected String type;
    @XmlAttribute(name = "name", required = true)
    protected String name;
    @XmlAttribute(name = "id", required = true)
    protected int id;

    /**
     * Obtiene el valor de la propiedad type.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Define el valor de la propiedad type.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Obtiene el valor de la propiedad name.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Define el valor de la propiedad name.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Obtiene el valor de la propiedad id.
     * 
     */
    public int getId() {
        return id;
    }

    /**
     * Define el valor de la propiedad id.
     * 
     */
    public void setId(int value) {
        this.id = value;
    }

}
